name: Check URLs

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * 0' # 5:17 AM every Sunday
  pull_request:
    branches: [ main ]
env:
  ignore_patterns: |
    http://localhost:4000
    https://preview.bssw.io
    https://github.com/<your-github-handle>
  ignore_dirs: |
    .github
    utils
    docs
  ignore_files: |
    foo

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Reformat enviornment variables
      id: setup_vars
      run: |
        set -x
        tmp=$(echo "${{ env.ignore_patterns }}" | tr '\n' ',' | sed -e 's/,,$//')
        echo "ignore_patterns=$tmp" >> $GITHUB_OUTPUT
        tmp=$(echo "${{ env.ignore_dirs }}" | sed -e 's@\(.*\)@"**/\1/**"@' | tr '\n' ',' | sed -e 's@,"\*\*//\*\*",$@@')
        echo "ignore_dirs=$tmp" >> $GITHUB_OUTPUT

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debugging Vars
      id: debug
      run: |
        echo "Got here 1"
        echo "${{ steps.setup_vars.outputs.ignore_patterns }}"
        echo "Got here 2"
        echo "${{ steps.setup_vars.outputs.ignore_dirs }}"
        echo "Got here 3"

    - name: Get Changed Files (for PRs)
      if: ${{ github.event_name == 'pull_request' }}
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        separator: ','
        files: '**.md'
        files_ignore: ${{ steps.setup_vars.outputs.ignore_dirs }}

    - name: Generate list of selected files to URL check 
      id: file_list
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
        else
          fcmd=""
          tmp=$(echo "${{ env.ignore_dirs }}" | tr '\n' ' ' | sed -e 's/  $//')
          for d in $ignore_dirs; do
              fcmd="$fcmd -name $d -prune -o "
          done
          echo "files=$(find . $fcmd -name '*.md' | tr '\n' ',')" >> $GITHUB_OUTPUT
        fi

    - name: Check URLs in selected files
      uses: urlstechie/urlchecker-action@0.0.34
      with:

        # Work only on markdown files
        file_types: .md

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # More verbose summary at the end of a run
        verbose: true

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3

        # Google Forms is having enormous timeouts
        timeout: 10

        # Exclude these patterns from the checker
        exclude_patterns: ${{ steps.setup_vars.outputs.ignore_patterns }}

        # Operate only on the specific list of files selected above
        include_files: "${{ steps.file_list.outputs.files }}"

#
# Description:
#
# Triggers in one of three ways; 1) manually, 2) scheduled weekly Sunday's 5:17 AM
# or 3) pull request
#
#
